import os

print("baba")

news_data = {
 'status': 'ok',
 'totalResults': 727,
 'articles':
  [
    {'source': {'id': None, 'name': 'Yahoo Entertainment'},
     'author': 'Ghazal Ahmed',
     'title': 'Tesla, Inc.\xa0(TSLA): AI and Autonomous Driving Drive Long-Term Bull Case Amid Q4 Delivery Projections',
     'description': 'We recently compiled a list of the 10 AI News You Can’t Miss. In this article, we are going to take a look at where Tesla, Inc. (NASDAQ:TSLA) stands against ...',
     'url': 'https://finance.yahoo.com/news/tesla-inc-tsla-ai-autonomous-153534984.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/R3DsTXHuX1Up50du0B.awA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzM-/https://media.zenfs.com/en/insidermonkey.com/1277c6032fd09b727a10249a170024cf',
     'publishedAt': '2024-12-26T15:35:34Z',
     'content': "We recently compiled a list of the 10 AI News You Can't Miss.\xa0In this article, we are going to take a look at where Tesla, Inc.\xa0(NASDAQ:TSLA) stands against the other AI stocks you can't miss.\r\nAccor… [+4911 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'},
     'author': 'Ramish Cheema',
     'title': 'Jim Cramer on Tesla, Inc (TSLA): ‘Shares Of Tesla Are Down About 13% Year To Date’',
     'description': 'We recently published an article titled Jim Cramer’s Bold Predictions About These 15 AI Stocks. In this article, we are going to take a look at where Tesla, ...',
     'url': 'https://finance.yahoo.com/news/jim-cramer-tesla-inc-tsla-051807610.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/R3DsTXHuX1Up50du0B.awA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzM-/https://media.zenfs.com/en/insidermonkey.com/1277c6032fd09b727a10249a170024cf',
     'publishedAt': '2024-12-30T05:18:07Z',
     'content': "We recently published an article titled Jim Cramer's Bold Predictions About These 15 AI Stocks.\xa0In this article, we are going to take a look at where Tesla, Inc (NASDAQ:TSLA) stands against the other… [+6993 chars]"},
    {'source': {'id': 'bloomberg', 'name': 'Bloomberg'},
     'author': 'John Gruber',
     'title': 'Bloomberg: Tim Cook Plans to Attend Trump’s Inauguration', 'description': None,
     'url': 'https://www.bloomberg.com/news/articles/2025-01-15/apple-s-tim-cook-plans-to-join-other-ceos-at-trump-inauguration',
     'urlToImage': None, 'publishedAt': '2025-01-15T20:46:35Z',
     'content': 'Marko Parker, reporting for Bloomberg:\n\n\n Apple Inc. CEO Tim Cook is planning to attend the inauguration of\nPresident-elect Donald Trump next week, the latest in a wave of\nSilicon Valley leaders trav… [+337 chars]'},
    {'source': {'id': None, 'name': 'Digital Trends'},
     'author': 'Christian de Looper',
     'title': 'Hyundai Ioniq 9 vs. Tesla Model Y: Does electric SUV beat the bestselling EV?',
     'description': 'The Hyundai Ioniq 9 is likely to be a stellar electric SUV -- but how does it compare with the bestselling EV, the Tesla Model Y?',
     'url': 'https://www.digitaltrends.com/cars/hyundai-ioniq-9-vs-tesla-model-y-does-electric-suv-beat-the-bestselling-ev/',
     'urlToImage': 'https://www.digitaltrends.com/wp-content/uploads/2024/11/hyundai-ioniq-9-7.jpg?resize=1200%2C630&p=1',
     'publishedAt': '2025-01-01T20:48:13Z',
     'content': 'Table of Contents\r\nTable of Contents\r\nDesign\r\nInterior and tech\r\nPerformance\r\nRange and charging\r\nPricing and availability\r\nOverall winner: Tesla Model Y\r\nThe long-awaited Hyundai Ioniq 9 is finally … [+6998 chars]'},
    {'source': {'id': 'time', 'name': 'Time'},
     'author': 'Andrew R. Chow',
     'title': 'How the Benefits—and Harms—of AI Grew in 2024',
     'description': 'In 2024, tech companies raced ahead with AI, driving markets and stirring regulators.',
     'url': 'https://time.com/7200444/how-ai-benefits-harms-grew-in-2024/',
     'urlToImage': 'https://api.time.com/wp-content/uploads/2024/12/nvidia-humanoid-robots-ai-tech-2024.jpg?quality=85&w=1024&h=628&crop=1',
     'publishedAt': '2024-12-30T12:00:00Z',
     'content': 'In 2024, both cutting-edge technology and the companies controlling it grew increasingly powerful, provoking euphoric wonderment and existential dread. Companies like Nvidia and Alphabet soared in va… [+7062 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Chris Katje',
     'title': "Tesla Stock 'Valuation Is Full': Analyst Flags Long-Term Growth Opportunities With Robotaxis, FSD",
     'description': 'A Tesla Inc (NASDAQ:TSLA) analyst highlighted the monetization opportunities for the company with its robotaxis and FSD. The Tesla Analyst: Goldman Sachs...',
     'url': 'https://finance.yahoo.com/news/tesla-stock-valuation-full-analyst-213016295.html',
     'urlToImage': 'https://media.zenfs.com/en/benzinga_79/d5ae5b7d546cd7b3166d5ef8a65cec87',
     'publishedAt': '2025-01-17T21:30:16Z',
     'content': "Tesla Stock 'Valuation Is Full': Analyst Flags Long-Term Growth Opportunities With Robotaxis, FSD\r\nBenzinga and Yahoo Finance LLC may earn commission or revenue on some items through the links below.… [+4029 chars]"},
    {'source': {'id': None, 'name': 'Jalopnik'}, 'author': 'Andy Kalmowitz',
     'title': 'Elon Musk Looks Ready To Cash In On $250 Million Trump Gamble',
     'description': 'Good morning and Happy New Year! It’s Thursday, January 2, 2025, and this is The Morning Shift, your daily roundup of the top automotive headlines from around the world, in one place. Here are the important stories you need to know.Read more...',
     'url': 'https://jalopnik.com/elon-musk-looks-ready-to-cash-in-on-250-million-trump-1851731024',
     'urlToImage': 'https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/7ae0632f65ead04045f6fa95ac349400.png',
     'publishedAt': '2025-01-02T15:15:00Z',
     'content': 'Good morning and Happy New Year! Its Thursday, January 2, 2025, and this is The Morning Shift, your daily roundup of the top automotive headlines from around the world, in one place. Here are the imp… [+11627 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'breakingthenews.net',
     'title': 'Musk urges UK Reform Party to replace Farage as leader',
     'description': 'Billionaire entrepreneur and Tesla Inc. CEO Elon Musk said on Sunday that the United Kingdom\'s Reform Party should replace Nigel Farage as its leader."The Reform Party needs a new leader. Farage doesn...',
     'url': 'https://biztoc.com/x/3c224f46a7e0ac16', 'urlToImage': 'https://biztoc.com/cdn/3c224f46a7e0ac16_s.webp',
     'publishedAt': '2025-01-05T16:11:00Z',
     'content': 'Billionaire entrepreneur and Tesla Inc. CEO Elon Musk said on Sunday that the United Kingdom\'s Reform Party should replace Nigel Farage as its leader."The Reform Party needs a new leader. Farage does… [+69 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Brody Ford, Spencer Soper and Katie Roof',
     'title': 'Car-Rental Startup Turo’s Safety Team Cuts Vacations Short After Deadly Attacks',
     'description': '(Bloomberg) -- Some workers on car-rental startup Turo Inc.’s trust and safety team have interrupted vacations to monitor and respond to the aftermath of...',
     'url': 'https://finance.yahoo.com/news/car-rental-startup-turo-safety-211246742.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/SAAnesKzuJX4..fxUIgS0w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/bloomberg_technology_68/568c3ba87bc6e91cb0de409455eca698',
     'publishedAt': '2025-01-02T21:12:46Z',
     'content': '(Bloomberg) -- Some workers on car-rental startup Turo Inc.s trust and safety team have interrupted vacations to monitor and respond to the aftermath of deadly attacks in Las Vegas and New Orleans, a… [+3883 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Kara Carlson',
     'title': 'Tesla Stock Surge Runs Up Against a Potential Annual Sales Drop',
     'description': '(Bloomberg) -- For all the exuberance about Tesla Inc. benefiting from Donald Trump’s return to the White House, Wall Street isn’t so sure the carmaker can...',
     'url': 'https://finance.yahoo.com/news/tesla-stock-surge-runs-against-125059167.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/qtrbXz5_ohzMn6Yz4JM3Pw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03NTE-/https://media.zenfs.com/en/bloomberg_markets_842/3a1cee63e4fc044bcd8d7c81c6891461',
     'publishedAt': '2024-12-31T12:50:59Z',
     'content': '(Bloomberg) For all the exuberance about Tesla Inc. (TSLA) benefiting from Donald Trumps return to the White House, Wall Street isnt so sure the carmaker can avoid its first annual sales decline in o… [+4137 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Tesla-Supplier Panasonic Energy Targets Reduced Reliance On China For US Battery Supplies, Says It Is 'No.1 Objective'",
     'description': 'Panasonic Energy, a key supplier for Tesla Inc. (NASDAQ:TSLA), is aiming to cut its reliance on China for electric vehicle battery supplies in the U.S. Allan Swan, President of Panasonic Energy of North America, emphasized that this transition is the company’…',
     'url': 'https://biztoc.com/x/a5abe85361fedd8c', 'urlToImage': 'https://biztoc.com/cdn/a5abe85361fedd8c_s.webp',
     'publishedAt': '2025-01-07T06:52:03Z',
     'content': 'Panasonic Energy, a key supplier for Tesla Inc. (NASDAQ:TSLA), is aiming to cut its reliance on China for electric vehicle battery supplies in the U.S. Allan Swan, President of Panasonic Energy of No… [+138 chars]'},
    {'source': {'id': None, 'name': 'Etf.com'}, 'author': 'Sumit Roy',
     'title': 'Tesla ETF Skids as Nvidia Unveils Toyota Deal at CES',
     'description': "The deal between the AI chip giant and the world's largest automaker dented shares of Tesla and a Tesla bull ETF on Tuesday.",
     'url': 'http://www.etf.com/sections/news/tesla-etf-skids-nvidia-unveils-toyota-deal-ces?utm_source=yahoo-finance&amp;utm_medium=rss&amp;utm_campaign=yahoo-finance-rss',
     'urlToImage': 'https://media.zenfs.com/en/indexuniverse.com/1791b6104e73194f412a6e0ec2f51314',
     'publishedAt': '2025-01-08T14:00:00Z',
     'content': 'ETF Investing Tools\r\nShares of the electric vehicle maker Tesla Inc. dropped about 4% Tuesday as investors digested comments from the CEO of a big partner and potential competitor.\r\nJensen Huang, CEO… [+2094 chars]'},
    {'source': {'id': None, 'name': 'Nakedcapitalism.com'}, 'author': 'Yves Smith',
     'title': 'What Should Tesla’s Stock Be Worth? Automaker, Stagnating Vehicle Sales like GM & Ford, Getting Overtaken by Competitors, Losing Share in the Booming EV Market?',
     'description': "Tesla is now just ar mid-size automaker amid EV competition that is eating its lunch. What might realistic valuations mean for Musk's clout?",
     'url': 'https://www.nakedcapitalism.com/2025/01/what-should-teslas-stock-be-worth-automaker-stagnating-vehicle-sales-like-gm-ford-getting-overtaken-by-competitors-losing-share-in-the-booming-ev-market.html',
     'urlToImage': 'https://www.nakedcapitalism.com/wp-content/uploads/2025/01/00-Tesla.png',
     'publishedAt': '2025-01-03T06:03:02Z',
     'content': 'Yves here. Below, Wolf Richter demonstrates how fabulously overvalued Tesla stock is. Yours truly is not a stock jockey, but even allowing for that, I have difficulty thinking of any previous case wh… [+7648 chars]'},
    {'source': {'id': None, 'name': 'BMWBLOG'}, 'author': 'Steven Paul',
     'title': 'The New BMW iX3 Could Be Tesla Model Y Juniper’s Toughest Competitor',
     'description': 'The Tesla Model Y has sold excellently since its introduction in 2017. Believe it or not, that was eight years ago – roughly the time it takes BMW to introduce a new model. And Tesla...\nFirst published by https://www.bmwblog.com',
     'url': 'https://www.bmwblog.com/2025/01/10/new-bmw-ix3-vs-tesla-model-y-juniper-2025-ev-competition/',
     'urlToImage': 'https://cdn.bmwblog.com/wp-content/uploads/2025/01/Tesla-model-y-juniper.jpg',
     'publishedAt': '2025-01-10T22:12:55Z',
     'content': 'The Tesla Model Y has sold excellently since its introduction in 2017. Believe it or not, that was eight years ago roughly the time it takes BMW to introduce a new model. And Tesla has sort of done t… [+3496 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Kaustubh Bagalkote',
     'title': "Elon Musk Calls Jeff Bezos' Ex-Wife MacKenzie Scott's $19 Billion Charitable Donations 'Concerning'",
     'description': 'Tesla Inc. CEO Elon Musk has raised fresh concerns about MacKenzie Scott‘s charitable donations, highlighting growing tensions over billionaire philanthropy ...',
     'url': 'https://finance.yahoo.com/news/elon-musk-calls-jeff-bezos-224312828.html',
     'urlToImage': 'https://media.zenfs.com/en/Benzinga/1dde8c4a5053d09cc12f94bf01f88801',
     'publishedAt': '2024-12-25T22:43:12Z',
     'content': 'Tesla Inc. CEO Elon Musk has raised fresh concerns about MacKenzie Scotts charitable donations, highlighting growing tensions over billionaire philanthropy and its societal impact.\r\nWhat Happened: Re… [+2090 chars]'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Tesla sales declined for first time in a decade',
     'description': "Tesla sales for 2024 declined for the first time in 10 years despite enticing financing offers and low-priced leases. CBS MoneyWarch correspondent Kelly O'Grady has more on the alarming trend. Also, Apple settles a lawsuit over user privacy.",
     'url': 'https://www.cbsnews.com/video/tesla-sales-declined-for-first-time-in-a-decade/',
     'urlToImage': 'https://assets3.cbsnewsstatic.com/hub/i/r/2025/01/02/a6f3cb0b-8d3d-40ec-8e49-d77dc8e6e396/thumbnail/1200x630/20add105f861a30d9f5cccfb22d5e6cc/cbsn-fusion-tesla-sales-declined-for-first-time-in-a-decade-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T19:49:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Tesla Cybertruck explodes outside Trump hotel in Las Vegas',
     'description': "One person is dead and seven others have been injured after a Tesla Cybertruck exploded outside the Trump Towers in Las Vegas, officials say. CBS News' Scott MacFarlane and Nicole Sganga have more on that incident and security considerations in cities amid th…",
     'url': 'https://www.cbsnews.com/video/cybertruck-explodes-outside-trump-hotel-in-las-vegas/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/01/b1bc5bc6-053c-4b63-92ae-588916a2c2ea/thumbnail/1200x630/540ea8645bebddaad3368f89710dc7be/cbsn-fusion-cybertruck-explodes-outside-trump-hotel-in-las-vegas-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-01T21:35:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Artificial intelligence was used in Tesla Cybertruck explosion, police say',
     'description': "Investigators say the devices used in the Tesla Cybertruck explosion were made with the help of artificial intelligence. CBS News' Andres Gutierrez has the latest.",
     'url': 'https://www.cbsnews.com/video/artificial-intelligence-was-used-in-tesla-cybertruck-explosion-police-say/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/08/adf30728-cf2e-47ce-ac2b-3bbe4b534ee1/thumbnail/1200x630/282189ee38effaa97fb7b9e1414a1e78/0108-cmo-vegas.jpg?v=6ffea931a1e284729a23a55e2e39c4e9',
     'publishedAt': '2025-01-08T14:18:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Cybertruck explosion outside Las Vegas Trump hotel investigated as possible act of terrorism',
     'description': "Investigators are treating Wednesday's Tesla Cybertruck explosion outside a Trump hotel in Las Vegas as a possible act of terrorism. CBS News correspondent Andres Gutierrez has more.",
     'url': 'https://www.cbsnews.com/video/cybertruck-explosion-outside-las-vegas-trump-hotel-investigated-as-possible-act-of-terrorism/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/02/ca05417d-c26e-461e-87c9-40854ee379c5/thumbnail/1200x630/adf6c593e0a164efe18522f3f51eaab5/cbsn-fusion-cybertruck-explosion-outside-las-vegas-trump-hotel-investigated-as-possible-act-of-terrorism-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T13:19:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Authorities give update on Cybertruck explosion at Trump hotel in Las Vegas',
     'description': 'Law enforcement provided more information Wednesday night on the deadly explosion of a Tesla Cybertruck Wednesday outside the Trump Towers in Las Vegas.',
     'url': 'https://www.cbsnews.com/video/authorities-give-update-on-cybertruck-explosion-at-trump-hotel-in-las-vegas/',
     'urlToImage': 'https://assets3.cbsnewsstatic.com/hub/i/r/2025/01/02/5364c7d3-6db7-4442-a84f-a7dc25b579eb/thumbnail/1200x630/59274560cc1085e86f76f5b7b12769dd/cbsn-fusion-authorities-give-update-on-cybertruck-explosion-at-trump-hotel-in-las-vegas-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T00:26:22Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Is Tesla, Inc. (TSLA) A Good Car Stock To Invest In Now?', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_e6b54a9d-48bc-4eaa-aa04-c80c0dc1a384',
     'urlToImage': None, 'publishedAt': '2024-12-29T12:36:08Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Is Tesla, Inc. (NASDAQ:TSLA) the Hottest Large-Cap Stock Right Now?', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_eb7d6aeb-1cef-4bbf-b467-5c1172c790cb',
     'urlToImage': None, 'publishedAt': '2025-01-05T14:17:31Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Is Tesla, Inc. (TSLA) the Biggest EV Stock In the World Heading Into 2025?', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_ec2d5adf-771a-4ab5-9299-2061f8cdb71e',
     'urlToImage': None, 'publishedAt': '2024-12-30T13:05:37Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Tesla, Inc. (TSLA)’s 2025 Vision: Will AI Drive Market Success?', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_44a5cf07-d495-4f0e-acf3-a2b7265ae285',
     'urlToImage': None, 'publishedAt': '2025-01-14T19:06:34Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Jim Cramer on Tesla, Inc. (TSLA): ‘When They Reported The Quarter It Was Bad’', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_b1a7b32a-f33b-41a4-8af7-b7c170705b4b',
     'urlToImage': None, 'publishedAt': '2025-01-15T17:43:35Z',
     'content': "If you click 'Accept all', we and our partners, including 239 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': None,
     'title': 'Why Tesla, Inc. (TSLA) Is the Best Environmental Stock to Invest in Right Now?', 'description': None,
     'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_cb91361b-78b8-418f-beed-ba9e04a01cd6',
     'urlToImage': None, 'publishedAt': '2024-12-31T09:36:57Z',
     'content': "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Bloomberg News',
     'title': 'China Discusses Sale of TikTok US to Musk as One Possible Option',
     'description': '(Bloomberg) -- Chinese officials are evaluating a potential option that involves Elon Musk acquiring the US operations of TikTok if the company fails to fend...',
     'url': 'https://finance.yahoo.com/news/china-discusses-sale-tiktok-us-000749646.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/fYMjhOMxymvSLUwXoASMPw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/bloomberg_technology_68/fa438935ea521eb72bcbbdd07f2ed2b5',
     'publishedAt': '2025-01-14T00:07:49Z',
     'content': '(Bloomberg) -- Chinese officials are evaluating a potential option that involves Elon Musk acquiring the US operations of TikTok if the company fails to fend off a controversial ban on the short-vide… [+6928 chars]'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'New information on suspect, contents of Cybertruck in Las Vegas explosion',
     'description': 'Investigators are learning more about the Tesla Cybertruck outside a Trump hotel in Las Vegas Thursday. CBS News correspondent Andres Gutierrez has more on what was found inside the vehicle and what we know about the suspect.',
     'url': 'https://www.cbsnews.com/video/new-information-on-contents-of-cybertruck-that-exploded-in-las-vegas-suspects-home-searched/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/02/5ce7e50f-0481-425c-993b-ed997a223842/thumbnail/1200x630/8a6dc30f2ca1acaaed12bc59a38f97f3/cbsn-fusion-new-information-on-contents-of-cybertruck-that-exploded-in-las-vegas-suspects-home-searched-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T16:20:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': '1 dead after Tesla Cybertruck explodes outside of Trump hotel in Las Vegas',
     'description': 'A Tesla Cybertruck explosion just outside of Trump hotel in Las Vegas is being investigated as a possible act of terrorism. One person inside the vehicle was killed and seven others nearby were injured.',
     'url': 'https://www.cbsnews.com/video/1-dead-after-tesla-cybertruck-explodes-outside-of-trump-hotel-in-las-vegas/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/02/d1aa9819-4ffa-48aa-96f2-635861aa07cb/thumbnail/1200x630/0fdda763b58dc6004f7dd1ff91208630/0102-cmo-cybertruck.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T14:39:16Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Driver in Tesla Cybertruck explosion shot himself before blast, authorities say',
     'description': "Investigators say the driver of a Tesla Cybertruck shot himself in the head before the vehicle exploded outside a Trump hotel in Las Vegas on Wednesday. CBS News' Andres Gutierrez has the latest.",
     'url': 'https://www.cbsnews.com/video/driver-in-tesla-cybertruck-explosion-shot-himself-before-blast-authorities-say/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/03/8a564184-2a53-41c1-8ac0-b1e63ed3d4bd/thumbnail/1200x630/d6f2a983c48859de3f379f21370ca0ef/0103-cmo-cybertruck.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-03T14:21:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Possible links between New Orleans truck attack and Vegas Cybertruck explosion outside Trump hotel?',
     'description': "Anna Schecter, senior coordinating producer for the CBS News Crime and Public Safety Unit, has a look at the investigations into Monday's New Orleans truck attack and the Tesla Cybertruck explosion outside a Trump hotel in Las Vegas.",
     'url': 'https://www.cbsnews.com/video/possible-links-between-new-orleans-truck-attack-and-cybertruck-explosion-outside-trump-hotel/',
     'urlToImage': 'https://assets2.cbsnewsstatic.com/hub/i/r/2025/01/02/0c20cd17-a0fe-4436-afaa-c07b95751cdc/thumbnail/1200x630/dfd96f132eba8084c9cc45dd049d1309/cbsn-fusion-possible-links-between-new-orleans-truck-attack-and-cybertruck-explosion-outside-trump-hotel-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T12:53:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Anthony Palazzo',
     'title': 'Chinese EV Makers Hit EU Wall as Tariffs Add to Import Costs',
     'description': '(Bloomberg) -- Chinese automakers captured their smallest share of Europe’s electric-vehicle market in eight months, after new tariffs added as much as 35...',
     'url': 'https://finance.yahoo.com/news/chinese-ev-makers-hit-eu-081008477.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/iJmXU4JhZQPFIG.qEsdV7g--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03OTQ-/https://media.zenfs.com/en/bloomberg_technology_68/bc4d8a4b015a02f9bf29a748758f6ae0',
     'publishedAt': '2024-12-23T08:10:08Z',
     'content': '(Bloomberg) -- Chinese automakers captured their smallest share of Europes electric-vehicle market in eight months, after new tariffs added as much as 35% to the cost of importing cars to the region.… [+3333 chars]'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Elon Musk comments on Las Vegas Cybertruck explosion',
     'description': "Tesla CEO Elon Musk is commenting on what he believes caused a Cybertruck to explode outside the Trump Towers in Las Vegas. This comes as more details emerge about the man who apparently rented the vehicle. KLAS' Brian Will has more on the investigation into …",
     'url': 'https://www.cbsnews.com/video/elon-musk-comments-on-las-vegas-cybertruck-explosion/',
     'urlToImage': 'https://assets3.cbsnewsstatic.com/hub/i/r/2025/01/02/3a0fe4c5-74c2-40b4-93dc-6f2e8edff35d/thumbnail/1200x630/bff73f2fd7834b08e2b2c87d16344bd6/cbsn-fusion-elon-musk-comments-on-las-vegas-cybertruck-explosion-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T17:53:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'Cybertruck explosion outside Trump Hotel in Las Vegas investigated as possible terror attack',
     'description': 'A Tesla Cyberstruck exploded outside Trump Towers in Las Vegas, killing a person inside and injuring seven others. Police are investigating it as a possible act of terrorism, multiple sources with knowledge of the investigation told CBS News. Andres Gutierrez…',
     'url': 'https://www.cbsnews.com/video/cybertruck-explosion-outside-trump-hotel-in-las-vegas-investigated-as-possible-terror-attack/',
     'urlToImage': 'https://assets2.cbsnewsstatic.com/hub/i/r/2025/01/02/bb8e0341-18b6-42e5-ae0f-8b4b2405a9b0/thumbnail/1200x630/79e6389a777a21d271f53c4ab5764e1a/0101-en-gutierrez.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T00:36:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'New details on Las Vegas Cybertruck explosion',
     'description': 'Officials in Las Vegas, Nevada, provided updates on the investigation into a Tesla Cybertruck explosion at the Trump Towers. Authorities believe Matthew Alan Livelsberger, an active duty member of the Army Special Forces, was behind the blast. They do not yet…',
     'url': 'https://www.cbsnews.com/video/new-details-on-las-vegas-cybertruck-explosion/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/02/1fe43b69-b33b-4a20-b958-f60237bd011d/thumbnail/1200x630/f14b44e5bb39d863be69e3e3f4f6ee1e/cbsn-fusion-new-details-on-las-vegas-cybertruck-explosion-thumbnail-3440542-640x360.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-02T20:29:19Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': 'cbs-news', 'name': 'CBS News'}, 'author': 'CBS News',
     'title': 'What to know about Turo, the car rental app used in New Orleans attack and Las Vegas bombing',
     'description': "The car rental app Turo is working to understand how two of its vehicles were used in the deadly New Orleans attack and Cybertruck bombing in Las Vegas. The Tesla Cybertruck that exploded outside of President-elect Donald Trump's Las Vegas hotel and the elect…",
     'url': 'https://www.cbsnews.com/video/what-to-know-turo-car-rental-app-new-orleans-attack-las-vegas-bombing/',
     'urlToImage': 'https://assets1.cbsnewsstatic.com/hub/i/r/2025/01/03/05bcd675-6e8d-4682-b8dd-63cae54e0516/thumbnail/1200x630/b0eb259fce89be255e558dd6e10ca867/cbsn-fusion-what-to-know-turo-car-rental-app-new-orleans-las-vegas-attacks-thumbnail.jpg?v=fa9977353833f46f40b07abcd9d5240b',
     'publishedAt': '2025-01-03T22:50:00Z',
     'content': 'Watch CBS News\r\nCopyright ©2025 CBS Interactive Inc. All rights reserved.\r\nGet browser notifications for breaking news, live events, and exclusive reporting.\r\nNot NowTurn On'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Craig Trudell',
     'title': 'Tesla Poised for $1 Billion Windfall From EU’s Emissions Curbs',
     'description': '(Bloomberg) -- Tesla Inc. could collect more than €1 billion ($1 billion) in compensation from rival automakers that need help meeting tougher pollution...',
     'url': 'https://finance.yahoo.com/news/tesla-poised-1-billion-windfall-114658652.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/JO8nRUfkWRht8YFP8Hi8FQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03Mzk-/https://media.zenfs.com/en/bloomberg_markets_842/4c0f18d8aac50587d2f69f24ec733203',
     'publishedAt': '2025-01-08T14:36:02Z',
     'content': '(Bloomberg) -- Tesla Inc. could collect more than 1 billion ($1 billion) in compensation from rival automakers that need help meeting tougher pollution standards in the European Union this year, UBS … [+3371 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Sara Dorn, Forbes Staff, \n Sara Dorn, Forbes Staff\n https://www.forbes.com/sites/saradorn/',
     'title': 'Will Mike Johnson Get Reelected As Speaker? Johnson Faces Right-Wing Pushback—Despite Trump And Musk’s Endorsements',
     'description': 'Johnson can afford to lose just one vote to be re-elected speaker.',
     'url': 'https://www.forbes.com/sites/saradorn/2025/01/02/will-mike-johnson-get-reelected-as-speaker-johnson-faces-right-wing-pushback-despite-trump-and-musks-endorsements/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/6776b277bee312a07d32ea12/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
     'publishedAt': '2025-01-02T15:38:01Z',
     'content': 'The House is set to vote Friday on whether to re-elect Rep. Mike Johnson, R-La., as speakerand while President-elect Donald Trumps endorsement should pave the way to his re-election, a small group of… [+3086 chars]'},
    {'source': {'id': None, 'name': 'MIT Technology Review'}, 'author': 'Gregory E. Epstein',
     'title': 'The cult of tech',
     'description': '“THE CULT OF THE FOUNDER.” “THE CULT OF THE TECH GENIUS.”\xa0 “Beware: Silicon Valley’s cultists want to turn you into a disruptive deviant.” “Tech’s cult of the founder bounces back.” “Silicon Valley’s Strange, Apocalyptic Cults.” “How the cult of personality a…',
     'url': 'https://www.technologyreview.com/2024/12/23/1107291/the-cult-of-tech/',
     'urlToImage': 'https://wp.technologyreview.com/wp-content/uploads/2024/12/icon.working-thumb.jpg?resize=1200,600',
     'publishedAt': '2024-12-23T21:00:00Z',
     'content': 'The headlines seem to write themselves (if that cliché is allowed anymore in the age of ChatGPT and generative AI). Tech is culty. But that is a metaphor, right? Right?!\xa0\r\nWhen I first saw Michael Sa… [+4247 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Rimmi Singhi',
     'title': 'Honda-Nissan Mega Merger Plans: A Bold Move to Survive EV Disruption',
     'description': "HMC-NSANY's potential $50B merger seeks to tackle EV challenges, cut costs and compete with Tesla and BYD, reshaping the future of Japan's auto industry.",
     'url': 'https://finance.yahoo.com/news/honda-nissan-mega-merger-plans-151800920.html',
     'urlToImage': 'https://media.zenfs.com/en/zacks.com/d4a4e04bc4eb132922905e770a7fa2d9',
     'publishedAt': '2024-12-24T15:18:00Z',
     'content': 'As the auto industry navigates transformative shifts, two of Japan’s largest automakers, Honda HMC and Nissan NSANY, are exploring a landmark merger. This bold move aims to create a roughly $50 billi… [+5339 chars]'},
    {'source': {'id': 'nbc-news', 'name': 'NBC News'}, 'author': 'Lora Kolodny, CNBC, Jennifer Elias, CNBC',
     'title': "Waymo dominated U.S. robotaxi market in 2024, but Tesla and Amazon's Zoox loom",
     'description': 'Despite General Motor’s decision to shutter its Cruise robotaxi business earlier this month, the U.S. has never been closer to a driverless future.',
     'url': 'https://www.nbcnews.com/business/autos/waymo-dominated-us-robotaxi-market-2024-tesla-amazons-zoox-loom-rcna185458',
     'urlToImage': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2024-12/241226-Waymo-aa-1126-6486a5.jpg',
     'publishedAt': '2024-12-26T16:34:47Z',
     'content': 'Despite\xa0General Motors\xa0decision to\xa0shutter\xa0its Cruise robotaxi business earlier this month, the U.S. has never been closer to a driverless future.\xa0\r\nFor the autonomous vehicle industry, 2024 will be … [+11451 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Pooja Rajkumari',
     'title': "Ark Invest's Cathie Wood Urges Trump's Incoming Administration To Implement Retroactive Tax Cuts For Economic Boost From January 1",
     'description': 'Cathie Wood, a well-known U.S. technology investor, is calling for clear tax policies from Donald Trump‘s incoming administration. What Happened: Wood...',
     'url': 'https://finance.yahoo.com/news/ark-invests-cathie-wood-urges-115812070.html',
     'urlToImage': 'https://media.zenfs.com/en/Benzinga/458de8ed0879bdba8e4464869bddb25a',
     'publishedAt': '2024-12-28T11:58:12Z',
     'content': "Ark Invest's Cathie Wood Urges Trump's Incoming Administration To Implement Retroactive Tax Cuts For Economic Boost From January 1\r\nCathie Wood, a well-known U.S. technology investor, is calling for … [+2340 chars]"},
    {'source': {'id': 'usa-today', 'name': 'USA Today'}, 'author': 'Andrea Riquier, USA TODAY',
     'title': 'Stocks surge Friday, beverage makers sink after surgeon general warning',
     'description': 'U.S. stocks were higher on Friday, but shares of alcoholic beverage makers were lower after the surgeon general announced a link to cancer.',
     'url': 'https://www.usatoday.com/story/money/markets/2025/01/03/nasdaq-leads-stocks-higher-but-beverage-makers-fall/77430000007/',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/4Zmre.2LkCghCPHE8Slf1Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/usa_today_money_325/67081f0790bb182f828e3dd0fea11eee',
     'publishedAt': '2025-01-03T15:59:23Z',
     'content': 'Wall Street sign and US flag\r\nU.S. stocks bounced higher on Friday, more than reversing a down first day of trading to start 2025.\r\nThe broad S&amp;P 500 index closed up by about 74 points, 1.3%, at … [+2049 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Alison Durkee, Forbes Staff, \n Alison Durkee, Forbes Staff\n https://www.forbes.com/sites/alisondurkee/',
     'title': 'This Tobacco Giant Was The Biggest Corporate Donor To The 2024 Presidential Race',
     'description': 'Billionaire business leaders shelled out during the presidential election, but corporations largely didn’t weigh in.',
     'url': 'https://www.forbes.com/sites/alisondurkee/2024/12/27/this-tobacco-giant-was-the-biggest-corporate-donor-to-the-2024-presidential-race/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/6765d81c92ff74ba7043bd76/0x0.jpg?format=jpg&crop=3416,1922,x0,y172,safe&height=900&width=1600&fit=bounds',
     'publishedAt': '2024-12-27T11:30:00Z',
     'content': 'While billionaire business leaders poured money into 2024s presidential race, businesses largely stayed awayyet the biggest corporate donor was a leading tobacco company that put its money behind Pre… [+8282 chars]'},
    {'source': {'id': 'al-jazeera-english', 'name': 'Al Jazeera English'}, 'author': 'Al Jazeera',
     'title': 'Trump critics say inauguration optics show oligarchy in action',
     'description': 'In a break with tradition, Silicon Valley CEOs feature prominently at presidential inauguration.',
     'url': 'https://www.aljazeera.com/news/2025/1/21/trump-critics-say-inauguration-optics-show-oligarchy-in-action',
     'urlToImage': 'https://www.aljazeera.com/wp-content/uploads/2025/01/AP25020716915144-1737434810_02df05-1737435793.jpg?resize=1200%2C630&quality=80',
     'publishedAt': '2025-01-21T06:49:42Z',
     'content': 'The influence of Silicon Valley was on display at Donald Trumps inauguration, with the 47th president of the United States taking the oath of office flanked by some of the most prominent CEOs of the … [+3977 chars]'},
    {'source': {'id': 'al-jazeera-english', 'name': 'Al Jazeera English'}, 'author': 'Al Jazeera',
     'title': 'Trump’s inauguration: Schedule of events and who will attend',
     'description': "A look at what will happen and who will be there for Donald Trump's historic return as US president.",
     'url': 'https://www.aljazeera.com/news/2025/1/20/trumps-inauguration-schedule-of-events-and-who-will-attend',
     'urlToImage': 'https://www.aljazeera.com/wp-content/uploads/2025/01/AP25019811473077-1737374683_6da019-1737375051.jpg?resize=1200%2C630&quality=80',
     'publishedAt': '2025-01-20T14:33:00Z',
     'content': 'For the second time, Donald Trump is set to be sworn in as president of the United States.\r\nTrumps inauguration in Washington, DC will kick off at noon local time (17:00 GMT). While most of the inaug… [+6014 chars]'},
    {'source': {'id': None, 'name': "Investor's Business Daily"}, 'author': None,
     'title': 'Dow Jones Futures Fall, But Nvidia Chipmaker Taiwan Semiconductor Lifts Techs',
     'description': "UnitedHealth dragged on the Dow after Wednesday's market rally.",
     'url': 'https://www.investors.com/market-trend/stock-market-today/dow-jones-futures-unitedhealth-nvidia-chipmaker-taiwan-semiconductor/',
     'urlToImage': 'https://www.investors.com/wp-content/uploads/2018/11/Stock-BikerMountain-01-adobe.jpg',
     'publishedAt': '2025-01-16T11:51:19Z',
     'content': 'Dow Jones futures fell slightly early Thursday amid mixed UnitedHealth (UNH) results while S&amp;P 500 futures and Nasdaq futures rose as Nvidia chipmaker Taiwan Semiconductor (TSM) lifted techs.\r\nBa… [+6443 chars]'},
    {'source': {'id': None, 'name': 'Memeorandum.com'}, 'author': None,
     'title': "Europe's Largest Pension Fund Sold Tesla Stake Over Musk's Pay (Cagan Koc/Bloomberg)",
     'description': "Cagan Koc / Bloomberg:\nEurope's Largest Pension Fund Sold Tesla Stake Over Musk's Pay\xa0 —\xa0 Europe's largest pension fund sold its entire €571 million ($585 million) stake in Tesla Inc. in the third quarter partly due to disagreement with Elon Musk's remunerati…",
     'url': 'https://www.memeorandum.com/250112/p34',
     'urlToImage': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iEtX.4RXPc1A/v1/1200x800.jpg',
     'publishedAt': '2025-01-13T00:40:00Z',
     'content': 'memeorandum is an auto-generated summary of the stories that US political commentators are discussing online right now.\r\nUnlike sister sites Techmeme and Mediagazer, it is not a human-edited news out… [+72 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Michael Shribman, Forbes Councils Member, \n Michael Shribman, Forbes Councils Member\n https://www.forbes.com/councils/forbesbusinesscouncil/people/michaelshribman/',
     'title': 'Business And Society: A Partnership For Progress And Impact',
     'description': 'The relationship between business and society is a powerful force for progress.',
     'url': 'https://www.forbes.com/councils/forbesbusinesscouncil/2025/01/09/business-and-society-a-partnership-for-progress-and-impact/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/677e9dade75edc1b9ada0b9b/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
     'publishedAt': '2025-01-09T14:45:00Z',
     'content': 'Michael Shribman is president and founder at APS Global Partners Inc. and Medias Health Inc.\r\ngetty\r\nThe connection between business and society is not a choiceit is a necessity. Having worked in var… [+7487 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Chris Katje',
     'title': 'US Electric Vehicle Sales Hit Record 1.3 Million Units In 2024, Despite Tesla Declines: Top 10 Bestselling Models',
     'description': "The U.S. automotive industry saw a record number of electric vehicles sold in 2024, with 1,301,411 units breaking last year's record with a 7.3% year-over...",
     'url': 'https://finance.yahoo.com/news/us-electric-vehicle-sales-hit-193014918.html',
     'urlToImage': 'https://media.zenfs.com/en/Benzinga/1094a81223f45e7ef62d07938b6a6093',
     'publishedAt': '2025-01-14T19:30:14Z',
     'content': 'US Electric Vehicle Sales Hit Record 1.3 Million Units In 2024, Despite Tesla Declines: Top 10 Bestselling Models\r\nThe U.S. automotive industry saw a record number of electric vehicles sold in 2024, … [+4093 chars]'},
    {'source': {'id': 'usa-today', 'name': 'USA Today'}, 'author': 'Andrea Riquier, USA TODAY',
     'title': "Why is the stock market down today? 'The market can't get a firm grip'",
     'description': 'There are big concerns on the horizon for markets in 2025, foreshadowed in early trading.',
     'url': 'https://www.usatoday.com/story/money/markets/2025/01/02/stocks-lower-to-start-2025/77402056007/',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/TDioxmQ6POVQmg1lWbsa_w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD0xODU2/https://media.zenfs.com/en/usa_today_money_325/c51c58eb24288b64937246b525c9ecb0',
     'publishedAt': '2025-01-02T18:48:53Z',
     'content': 'Markets seesawed on the first trading day of 2025 as investors grappled with big questions ahead of a change of power in Washington.\r\nU.S. stocks jumped in early trading, but by early afternoon the S… [+2131 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'GuruFocus, Contributor, \n GuruFocus, Contributor\n https://www.forbes.com/sites/gurufocus/',
     'title': 'Rigetti Computing: An Egregiously Overvalued Quantum Computing Stock',
     'description': 'Rigetti Computing is at the forefront of the quantum computing industry, but the company has a speculative stock valuation.',
     'url': 'https://www.forbes.com/sites/gurufocus/2025/01/10/rigetti-computing-an-egregiously-overvalued-quantum-computing-stock/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/678133b9e8a6f26057c367ce/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
     'publishedAt': '2025-01-10T14:57:55Z',
     'content': 'By Oliver Rodzianko\r\nSummary\r\n<ul><li>Rigetti, a top superconducting-qubit pioneer, traded at ~250 P/S, far exceeding rational valuations despite potential 50%+ annual revenue growth.</li><li>Stock p… [+9597 chars]'},
    {'source': {'id': None, 'name': 'Boston Herald'}, 'author': 'Bloomberg News',
     'title': 'Burning Teslas in LA add to toxic mix hindering California wildfire cleanup',
     'description': 'Lithium batteries from Tesla Inc., along with those from other carmakers, have added to the mix of toxic materials requiring specialized removal in the wake of the fires, delaying the fire victims’ return to their properties.',
     'url': 'https://www.bostonherald.com/2025/01/18/burning-teslas-in-la-add-to-toxic-mix-hindering-california-wildfire-cleanup/',
     'urlToImage': 'https://www.bostonherald.com/wp-content/uploads/2025/01/BIZ-AUTO-TESLA-WILDFIRES-ZUM.jpg?w=1024&h=683',
     'publishedAt': '2025-01-18T23:58:52Z',
     'content': 'Lithium batteries from Tesla Inc., along with those from other carmakers, have added to the mix of toxic materials requiring specialized removal in the wake of the fires, delaying the fire victims re… [+79 chars]'},
    {'source': {'id': None, 'name': "Investor's Business Daily"},
     'author': "HARRISON MILLER, Investor's Business Daily",
     'title': "Stock Market Holidays 2024/25: The New Year's Week Market Schedule",
     'description': 'Look at these stock market holidays in 2024 to find out whether financial markets will be open or closed.',
     'url': 'https://www.investors.com/research/stock-market-holidays-24-25-christmas-new-years/',
     'urlToImage': 'https://www.investors.com/wp-content/uploads/2018/12/Stock-NYSE-09-adobe.jpg',
     'publishedAt': '2024-12-31T12:18:54Z',
     'content': 'The Nasdaq, S&amp;P 500 and Dow industrial indexes have rallied through 2024, rising to record highs in December. That leaves the market in a healthy position as the market prepares to enter 2025.\r\nF… [+3007 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Mary Whitfill Roeloffs, Forbes Staff, \n Mary Whitfill Roeloffs, Forbes Staff\n https://www.forbes.com/sites/maryroeloffs/',
     'title': 'Inauguration Photos: Logan And Jake Paul Rub Elbows With Billionaires At Trump Swearing-In',
     'description': "Guests are arriving at the Capitol Rotunda ahead of Donald Trump's swearing in ceremony at noon.",
     'url': 'https://www.forbes.com/sites/maryroeloffs/2025/01/20/inauguration-photos-logan-and-jake-paul-rub-elbows-with-billionaires-at-trump-swearing-in/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/678e6ef3a1ee47f6ebdc4bef/0x0.jpg?format=jpg&crop=4000,2251,x0,y0,safe&height=900&width=1600&fit=bounds',
     'publishedAt': '2025-01-20T15:52:07Z',
     'content': 'Guests including Amazon founder Jeff Bezos, Argentinian President Javier Milei, Chinese Vice President Han Zheng and internet personalities Jake and Logan Paul are arriving at the U.S. Capitol, which… [+4019 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Lynn Doan and Debby Wu',
     'title': 'Tencent Shares Decline After US Adds Company to\xa0Chinese Military Blacklist',
     'description': '(Bloomberg) -- The US has blacklisted Tencent Holdings Ltd. and Contemporary Amperex Technology Co. Ltd. for alleged links to the Chinese military, targeting...',
     'url': 'https://finance.yahoo.com/news/tencent-shares-decline-us-adds-182247122.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/0QnE9jj60FGF6EShPCR_Cg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/bloomberg_markets_842/7a4a07d1f34abbae6b8265fcbfd3969e',
     'publishedAt': '2025-01-07T01:33:33Z',
     'content': '(Bloomberg) -- The US has blacklisted Tencent Holdings Ltd. and Contemporary Amperex Technology Co. Ltd. for alleged links to the Chinese military, targeting the worlds biggest gaming publisher and t… [+4889 chars]'},
    {'source': {'id': None, 'name': 'Benzinga'}, 'author': 'Pooja Rajkumari',
     'title': "Ark Invest's Cathie Wood Urges Trump's Incoming Administration To Implement Retroactive Tax Cuts For Economic Boost From January 1",
     'description': "Despite some market fluctuations, Wood remains hopeful about the ongoing influence of the 'Trump bump' on innovation-driven industries.",
     'url': 'https://www.benzinga.com/news/24/12/42713490/ark-invests-cathie-wood-urges-trumps-incoming-administration-to-implement-retroactive-tax-cuts-for-e',
     'urlToImage': 'https://cdn.benzinga.com/files/images/story/2024/12/28/Cathie-Woods-Thursday-Moves-Dumps-Buzzin.jpeg?width=1200&height=800&fit=crop',
     'publishedAt': '2024-12-28T13:58:12Z',
     'content': 'Cathie Wood, a well-known U.S. technology investor, is calling for clear tax policies from\xa0Donald Trump‘s incoming administration.\r\nWhat Happened: Wood proposes that tax cuts be retroactively applied… [+2538 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Esha Dey and Bailey Lipschultz',
     'title': 'S&P’s $18 trillion rally threatened by psychology of 5% yields',
     'description': '(Bloomberg) -- For years it’s seemed like nothing could stop the stock market’s inexorable march higher, as the S&P 500 Index soared more than 50% from the...',
     'url': 'https://finance.yahoo.com/news/p-18-trillion-rally-threatened-130007234.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/55HcOyVwADF41NPDdlAaIg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/os/creatr-uploaded-images/2025-01/756ddc70-d0ef-11ef-bfdb-bdf352971134',
     'publishedAt': '2025-01-12T13:00:07Z',
     'content': '(Bloomberg) For years its seemed like nothing could stop the stock markets inexorable march higher, as the S&amp;P 500 Index soared more than 50% from the start of 2023 to the end of 2024, adding $18… [+6740 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Talha Qureshi',
     'title': 'Is NIO Inc. (NIO) Among the Best Long-Term Penny Stocks to Buy According to Hedge Funds?',
     'description': 'We recently published a list of the 12 Best Long-Term Penny Stocks to Buy According to Hedge Funds. In this article, we are going to take a look at where NIO...',
     'url': 'https://finance.yahoo.com/news/nio-inc-nio-among-best-100620302.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/fbe9iN5R78tj2Fp19dSd2w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzM-/https://media.zenfs.com/en/insidermonkey.com/d02deb0aeed9330fc652aa9fa43c9dea',
     'publishedAt': '2025-01-04T10:06:20Z',
     'content': 'On December 3rd, Bob Kaynor, CFA, Head of US Small &amp; Midcap Equities at Schroders, provided a comprehensive outlook for small-cap stocks in 2025, emphasizing their potential as a cost-effective i… [+5329 chars]'},
    {'source': {'id': None, 'name': 'Securityaffairs.com'}, 'author': 'Pierluigi Paganini',
     'title': 'ZAGG disclosed a data breach that exposed its customers’ credit card data',
     'description': 'ZAGG Inc. notifies customers of credit card data breach, after threat actors hacked a third-party app from its e-commerce provider. ZAGG Inc. disclosed a data breach that exposed its customers’ credit card data after threat actors hacked a third-party applica…',
     'url': 'https://securityaffairs.com/172434/data-breach/zagg-credit-card-data-data-breach.html',
     'urlToImage': 'https://securityaffairs.com/wp-content/uploads/2012/04/data-breach.jpg',
     'publishedAt': '2024-12-30T00:04:23Z',
     'content': "ZAGG disclosed a data breach that exposed its customers' credit card data\r\n\xa0|\xa0China-linked APT Salt Typhoon breached a ninth U.S. telecommunications firm\r\n\xa0|\xa0SECURITY AFFAIRS MALWARE NEWSLETTER ROUND… [+126957 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Ramish Cheema',
     'title': 'Salesforce (CRM) Bounces Back: Cramer Praises Agentforce’s Strong Growth Despite Analyst Doubts',
     'description': 'We recently published a list of Jim Cramer Discussed These 29 Stocks Ahead Of Major AI Event. In this article, we are going to take a look at where...',
     'url': 'https://finance.yahoo.com/news/salesforce-crm-bounces-back-cramer-220235597.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/V4tGuBo0fm2vOSewxPjpmw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzM-/https://media.zenfs.com/en/insidermonkey.com/057172d1bddd5e7eaee5fc08e2756794',
     'publishedAt': '2025-01-10T22:02:35Z',
     'content': 'We recently published a list of Jim Cramer Discussed These 29 Stocks Ahead Of Major AI Event. In this article, we are going to take a look at where Salesforce, Inc. (NYSE:CRM) stands against other st… [+6247 chars]'},
    {'source': {'id': None, 'name': 'SiliconANGLE News'}, 'author': 'Duncan Riley',
     'title': 'Tesla Cybertruck explosion outside Trump Hotel leaves one dead, FBI investigates possible terrorism',
     'description': 'One person has died and seven others were injured when a Tesla Inc. Cybertruck exploded outside of the Trump International Hotel in Las Vegas in what may have been a targeted attack. According to local media reports, the Cybertruck exploded at about 8:40 a.m.…',
     'url': 'https://siliconangle.com/2025/01/01/tesla-cybertruck-explosion-outside-trump-hotel-leaves-one-dead-fbi-investigates-possible-terrorism/',
     'urlToImage': 'https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2025/01/cybertruckfire.png',
     'publishedAt': '2025-01-01T23:53:23Z',
     'content': 'One person has died and seven others were injured when a Tesla Inc. Cybertruck exploded outside of the Trump International Hotel in Las Vegas in what may have been a targeted attack.\r\nAccording to lo… [+3017 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Sara Dorn, Forbes Staff, \n Sara Dorn, Forbes Staff\n https://www.forbes.com/sites/saradorn/',
     'title': 'The Billionaires Trump’s Picked For Next Administration: Elon Musk, Tilman Fertitta And More',
     'description': 'Trump tapped Houston Rockets owner Tilman Fertitta for ambassador to Italy—putting him on a growing list of billionaires selected for administration roles.',
     'url': 'https://www.forbes.com/sites/saradorn/2024/12/22/the-billionaires-trumps-picked-for-next-administration-elon-musk-tilman-fertitta-and-more/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/6750cd5f7e3e88c07b0188aa/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
     'publishedAt': '2024-12-22T15:58:09Z',
     'content': 'President-elect Donald Trump is on track to break the record he set in 2016 for appointing the wealthiest cabinet in history, tapping these billionaires for his next administration.\r\nElon Musk speaks… [+4660 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Ed Garsten, Senior Contributor, \n Ed Garsten, Senior Contributor\n https://www.forbes.com/sites/edgarsten/',
     'title': 'It’s Going To Be A Bumpy Road To EV Adoption, Study Shows',
     'description': 'That study, however comes as EV sales in the U.S. surged in 2024 with predictions by other organizations that trend will continue this year.',
     'url': 'https://www.forbes.com/sites/edgarsten/2025/01/17/its-going-to-be-a-bumpy-road-to-ev-adoption-study-shows/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/678a88d1ec3def898d105bc1/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
     'publishedAt': '2025-01-17T16:59:08Z',
     'content': 'A global study by Tata Consultancy Services reveals consumer enthusiasm for EVs is offset by ... [+] concerns from manufacturers. (Photo by Smith Collection/Gado/Getty Images)\r\nGado via Getty Images\r… [+5861 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Ed Garsten, Senior Contributor, \n Ed Garsten, Senior Contributor\n https://www.forbes.com/sites/edgarsten/',
     'title': 'Bumpy Road To EV Adoption Tata Study Shows',
     'description': 'That study, however comes as EV sales in the U.S. surged in 2024 with predictions by other organizations that trend will continue this year.',
     'url': 'https://www.forbes.com/sites/edgarsten/2025/01/17/bumpy-road-to-ev-adoption-tata-study-shows/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/678a88d1ec3def898d105bc1/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
     'publishedAt': '2025-01-17T16:59:08Z',
     'content': 'A global study by Tata Consultancy Services reveals consumer enthusiasm for EVs is offset by ... [+] concerns from manufacturers. (Photo by Smith Collection/Gado/Getty Images)\r\nGado via Getty Images\r… [+5861 chars]'},
    {'source': {'id': None, 'name': 'SiliconANGLE News'}, 'author': 'Kyt Dotson',
     'title': 'China’s AgiBot releases large-scale humanoid robot AI dataset for everyday activities',
     'description': 'AgiBot, or Zhiyuan Robotics, a Chinese robotics firm aimed at building and innovating humanoid robotics today announced it’s releasing what it says is the largest robotic learning dataset for advancing artificial intelligence foundation models for human-like …',
     'url': 'https://siliconangle.com/2024/12/30/chinas-agibot-releases-large-scale-humanoid-robot-ai-dataset-everyday-activities/',
     'urlToImage': 'https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2024/12/agibot-world-image.png',
     'publishedAt': '2024-12-30T18:15:03Z',
     'content': 'AgiBot, or Zhiyuan Robotics, a Chinese robotics firm aimed at building and innovating humanoid robotics today announced it’s releasing what it says is the largest robotic learning dataset for advanci… [+3759 chars]'},
    {'source': {'id': 'newsweek', 'name': 'Newsweek'}, 'author': 'Matthew Impelli',
     'title': 'US Regulators Open Probe Into Tesla Vehicles Over Remote Driving Feature',
     'description': 'The latest inquiry comes on the heels of an October investigation into Tesla\'s "Full Self-Driving" system.',
     'url': 'https://www.newsweek.com/tesla-self-driving-feature-investigation-national-highway-traffic-safety-administration-2011309',
     'urlToImage': 'https://d.newsweek.com/en/full/2558817/tesla.jpg', 'publishedAt': '2025-01-07T22:02:15Z',
     'content': 'U.S. regulators on Tuesday announced an investigation into 2.6 million Tesla vehicles following reports of crashes linked to technology that enables drivers to use a smartphone app to remotely summon… [+3548 chars]'},
    {'source': {'id': None, 'name': 'Luxuo.com'}, 'author': 'Sanjeeva Suresh',
     'title': 'Stichting Pensioenfonds ABP Cuts Tesla Ties Amid Controversy',
     'description': 'Europe’s largest pension fund divests its USD 585 million stake in Tesla, citing concerns over Elon Musk’s pay package and poor working conditions.\nThe post Stichting Pensioenfonds ABP Cuts Tesla Ties Amid Controversy appeared first on LUXUO.',
     'url': 'https://www.luxuo.com/business/stichting-pensioenfonds-abp-cuts-tesla-ties-amid-controversy.html',
     'urlToImage': 'https://cdn.luxuo.com/2025/01/Tesla-Elon-Musk-featured-image-01.jpg',
     'publishedAt': '2025-01-14T06:58:20Z',
     'content': 'Europes largest pension fund divests its USD 585 million stake in Tesla, citing concerns over Elon Musks pay package and poor working conditions.\r\nEuropes largest pension fund Stichting Pensioenfonds… [+4040 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Ramish Cheema',
     'title': 'Jim Cramer on Uber Technologies, Inc. (UBER): ‘It Is Up A Lot This Month, So Let’s Be Careful And Only Buy Some, Not All’',
     'description': 'We recently compiled a list of the Jim Cramer’s Bearish Calls: 10 Tech Stocks Heading for a Crash. In this article, we are going to take a look at where Uber...',
     'url': 'https://finance.yahoo.com/news/jim-cramer-uber-technologies-inc-180554046.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/GjtvmBhItrilu8Ag7qjwaA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzM-/https://media.zenfs.com/en/insidermonkey.com/1b0d24331c5749b8809056a69d9d96ee',
     'publishedAt': '2024-12-27T18:05:54Z',
     'content': "For Jim Cramer, tech stocks and the Federal Reserve's interest rate cuts are a major talking point. Investors continued to deal with an uncertain macroeconomic picture that was complicated by a 'bull… [+7473 chars]"},
    {'source': {'id': None, 'name': 'Macdailynews.com'}, 'author': 'MacDailyNews',
     'title': 'Apple CEO Tim Cook to attend President Trump’s inauguration',
     'description': 'Apple CEO Tim Cook is set to attend the upcoming inauguration of President-elect Donald Trump, joining a significant group of Silicon Valley…\nThe post Apple CEO Tim Cook to attend President Trump’s inauguration appeared first on MacDailyNews.',
     'url': 'https://macdailynews.com/2025/01/16/apple-ceo-tim-cook-to-attend-president-trumps-inauguration/',
     'urlToImage': 'https://149359564.v2.pressablecdn.com/wp-content/uploads/2017/09/170927_trump_cook.jpg',
     'publishedAt': '2025-01-16T15:19:06Z',
     'content': 'Apple CEO Tim Cook and U.S. President Donald Trump at tech summit in June 2017\r\nApple CEO Tim Cook is set to attend the upcoming inauguration of President-elect Donald Trump, joining a significant gr… [+1985 chars]'},
    {'source': {'id': None, 'name': 'Insurance Journal'}, 'author': 'Admin',
     'title': 'Musk’s Massive Tesla Lithium Plant Hunts for Water in Drought-Hit Texas',
     'description': 'Twenty miles outside Corpus Christi, Texas — an area so dry the local water company distributes shower timers at high school football games — the world’s richest man is nearly done building a lithium refinery that could require as much …',
     'url': 'https://www.insurancejournal.com/news/southcentral/2025/01/07/807193.htm',
     'urlToImage': 'https://www.insurancejournal.com/app/uploads/2025/01/422459015.jpg',
     'publishedAt': '2025-01-07T17:19:32Z',
     'content': 'Twenty miles outside Corpus Christi, Texas an area so dry the local water company distributes shower timers at high school football games the world’s richest man is nearly done building a lithium ref… [+5936 chars]'},
    {'source': {'id': None, 'name': 'Forbes'},
     'author': 'Jamie Gold, Senior Contributor, \n Jamie Gold, Senior Contributor\n https://www.forbes.com/sites/jamiegold/',
     'title': 'Design And Tech Pros Predict Top Smart Home Trends For 2025',
     'description': 'I reached out by email to leaders in the home design and technology worlds for their insights on what they see coming our way this year.',
     'url': 'https://www.forbes.com/sites/jamiegold/2025/01/07/design-and-tech-pros-predict-top-smart-home-trends-for-2025/',
     'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/677c4e8a28817920e973c9a2/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
     'publishedAt': '2025-01-07T11:00:00Z',
     'content': 'One of the top uses for smart home technology this season, experts predict, will be energy ... [+] management.\r\nSavant Systems, Inc. // Wellness by Design Bonus Chapter (2023)\r\nIve been bullish on sm… [+7716 chars]'},
    {'source': {'id': None, 'name': 'SiliconANGLE News'}, 'author': 'Duncan Riley',
     'title': 'Inflection point: ChatGPT was used to plan Las Vegas Cybertruck explosion',
     'description': 'Throughout the history of humanity, every new invention, despite the best intentions, often ends up being used for wrongdoing. And when new inventions are used that way, those inventions often hit an inflection point. 2025\xa0started\xa0with a Tesla Inc. Cybertruck…',
     'url': 'https://siliconangle.com/2025/01/07/inflection-point-chatgpt-used-plan-las-vegas-cybertruck-explosion/',
     'urlToImage': 'https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2025/01/cybertruck.png',
     'publishedAt': '2025-01-08T00:26:48Z',
     'content': 'Throughout the history of humanity, every new invention, despite the best intentions, often ends up being used for wrongdoing. And when new inventions are used that way, those inventions often hit an… [+3297 chars]'},
    {'source': {'id': None, 'name': 'MarketWatch'}, 'author': 'Joseph Adinolfi',
     'title': 'Stocks are skipping the ‘Santa Claus rally’ again this year. That doesn’t bode well for January.',
     'description': 'Santa Claus is leaving investors in the lurch once again in 2024 as U.S. stocks have struggled during the typically bullish home stretch of the year.',
     'url': 'https://www.marketwatch.com/story/stocks-are-skipping-the-santa-claus-rally-again-this-year-that-doesnt-bode-well-for-january-ee018756',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/cCZinXE4VtV54F4Y7hIrxw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02MDA-/https://media.zenfs.com/en/marketwatch_hosted_869/7723d6053edd24ef08a57a17eaf64da4',
     'publishedAt': '2024-12-31T09:37:00Z',
     'content': 'Investors look set to be disappointed as the Santa Claus rally has so far failed to materialize for the second year in a row. - AFP via Getty Images\r\nSanta Claus is leaving investors in the lurch onc… [+5924 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Stock Position Increased by Udine Wealth Management Inc.',
     'description': 'Udine Wealth Management Inc. increased its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 3.6% in the 4th quarter, according to its most recent disclosure with the SEC. The firm owned 9,833 shares of the electric vehicle producer’s stock after acquiri…',
     'url': 'https://www.etfdailynews.com/2025/01/21/tesla-inc-nasdaqtsla-stock-position-increased-by-udine-wealth-management-inc/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-21T09:01:00Z',
     'content': 'Udine Wealth Management Inc. increased its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 3.6% in the 4th quarter, according to its most recent disclosure with the SEC. The firm owned 9,833 s… [+6081 chars]'},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Richard Henderson',
     'title': 'How $10,000 Fared in 2024 Across a Range of Standout Investments',
     'description': '(Bloomberg) -- Wars in Europe and the Middle East. Global political upheaval. Angst over a potential US recession. These and other pitfalls stalked markets...',
     'url': 'https://finance.yahoo.com/news/10-000-fared-2024-across-233901869.html',
     'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/UpphBvnDB_0AlzITcIC6mg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/os/creatr-uploaded-images/2025-01/16daf2b0-c83e-11ef-b7fd-9bb5fbbd13cc',
     'publishedAt': '2024-12-31T23:39:01Z',
     'content': '(Bloomberg) Wars in Europe and the Middle East. Global political upheaval. Angst over a potential US recession. These and other pitfalls stalked markets in 2024 but in the end investors who embraced … [+2790 chars]'},
    {'source': {'id': None, 'name': 'Lifesciencesworld.com'}, 'author': 'LSW Team',
     'title': 'Why was venza discontinued?',
     'description': 'Why Was Venza Discontinued? Venza, a popular electric vehicle (EV) brand, was discontinued by its parent company, NIO Inc., in […]\nThe post Why was venza discontinued? appeared first on Life Sciences World.',
     'url': 'https://lifesciencesworld.com/why-was-venza-discontinued/',
     'urlToImage': 'https://lifesciencesworld.com/wp-content/uploads/2024/12/featured.png',
     'publishedAt': '2025-01-17T10:58:31Z',
     'content': 'Why Was Venza Discontinued?\r\nVenza, a popular electric vehicle (EV) brand, was discontinued by its parent company, NIO Inc., in 2022. The decision to discontinue Venza was a significant one, and it r… [+4381 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'breakingthenews.net',
     'title': 'Tesla recalls 239,382 vehicles in US',
     'description': 'Tesla Inc. recalled 239,382 cars in the United States, according to the National Highway Safety Administration report published on Friday. More to come......',
     'url': 'https://biztoc.com/x/46a87c190a179068', 'urlToImage': 'https://biztoc.com/cdn/46a87c190a179068_s.webp',
     'publishedAt': '2025-01-10T10:39:45Z',
     'content': 'Tesla Inc. recalled 239,382 cars in the United States, according to the National Highway Safety Administration report published on Friday. More to come......\r\nThis story appeared on breakingthenews.n… [+23 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Versant Capital Management Inc Grows Stock Holdings in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Versant Capital Management Inc grew its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 24.5% in the fourth quarter, according to its most recent filing with the Securities & Exchange Commission. The institutional investor owned 3,892 shares of the ele…',
     'url': 'https://www.etfdailynews.com/2025/01/03/versant-capital-management-inc-grows-stock-holdings-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-03T11:26:49Z',
     'content': 'Versant Capital Management Inc grew its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 24.5% in the fourth quarter, according to its most recent filing with the Securities &amp; Exchange Comm… [+5829 chars]'},
    {'source': {'id': None, 'name': 'New York Post'}, 'author': 'Ariel Zilber',
     'title': 'Tech CEO ran red light ‘to save my life’ after self-driving Tesla put him in path of oncoming train',
     'description': 'Jesse Lyu posted video showing self-driving software steer his Tesla onto the tracks of the Metro E Line light rail service in Santa Monica.',
     'url': 'https://nypost.com/2025/01/06/business/tech-ceo-ran-a-red-light-to-save-my-life-after-self-driving-tesla-put-him-in-path-of-oncoming-train/',
     'urlToImage': 'https://nypost.com/wp-content/uploads/sites/2/2025/01/tech-ceo-says-had-ran-96324072.jpg?quality=75&strip=all&w=1024',
     'publishedAt': '2025-01-06T16:52:29Z',
     'content': 'A Silicon Valley tech executive is thankful to be alive after his self-driving Tesla led him onto the tracks of a light rail service — forcing him to run a red light to avoid getting rammed by an onc… [+3368 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Neville Rodie & Shaw Inc. Acquires Shares of 549 Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Neville Rodie & Shaw Inc. bought a new position in Tesla, Inc. (NASDAQ:TSLA – Free Report) during the fourth quarter, according to its most recent disclosure with the SEC. The institutional investor bought 549 shares of the electric vehicle producer’s stock, …',
     'url': 'https://www.etfdailynews.com/2025/01/07/neville-rodie-shaw-inc-acquires-shares-of-549-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-07T08:55:14Z',
     'content': 'Neville Rodie &amp; Shaw Inc. bought a new position in Tesla, Inc. (NASDAQ:TSLA – Free Report) during the fourth quarter, according to its most recent disclosure with the SEC. The institutional inves… [+5699 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'breakingthenews.net',
     'title': 'Musk: Tesla senior team investigating Cybertruck explosion',
     'description': 'Billionaire entrepreneur and SpaceX and Tesla Inc. CEO Elon Musk took to social media platform X to announce that the entire Tesla team is investigating the Las Vegas Cybertruck explosion at Trump Tow...',
     'url': 'https://biztoc.com/x/1653ff46dd7cbdc3', 'urlToImage': 'https://biztoc.com/cdn/1653ff46dd7cbdc3_s.webp',
     'publishedAt': '2025-01-01T21:20:15Z',
     'content': 'Billionaire entrepreneur and SpaceX and Tesla Inc. CEO Elon Musk took to social media platform X to announce that the entire Tesla team is investigating the Las Vegas Cybertruck explosion at Trump To… [+69 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Bard Financial Services Inc. Reduces Stock Position in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Bard Financial Services Inc. trimmed its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 0.4% during the third quarter, according to the company in its most recent 13F filing with the Securities and Exchange Commission. The institutional investor owned…',
     'url': 'https://www.etfdailynews.com/2025/01/01/bard-financial-services-inc-reduces-stock-position-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-01T08:58:45Z',
     'content': 'Bard Financial Services Inc. trimmed its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 0.4% during the third quarter, according to the company in its most recent 13F filing with the Securiti… [+6494 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Financial Management Professionals Inc. Has $1.62 Million Stake in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Financial Management Professionals Inc. reduced its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 11.1% in the 4th quarter, according to its most recent Form 13F filing with the Securities and Exchange Commission (SEC). The firm owned 3,998…',
     'url': 'https://www.etfdailynews.com/2025/01/21/financial-management-professionals-inc-has-1-62-million-stake-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-21T12:37:03Z',
     'content': 'Financial Management Professionals Inc. reduced its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 11.1% in the 4th quarter, according to its most recent Form 13F filing with the Se… [+6406 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Harbor Capital Advisors Inc. Sells 600 Shares of Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Harbor Capital Advisors Inc. decreased its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 38.9% during the 4th quarter, according to its most recent filing with the Securities and Exchange Commission (SEC). The firm owned 941 shares of the e…',
     'url': 'https://www.etfdailynews.com/2025/01/15/harbor-capital-advisors-inc-sells-600-shares-of-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-15T08:46:56Z',
     'content': 'Harbor Capital Advisors Inc. decreased its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 38.9% during the 4th quarter, according to its most recent filing with the Securities and E… [+6522 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Shares Bought by GAMMA Investing LLC',
     'description': 'GAMMA Investing LLC raised its stake in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 35.4% during the 4th quarter, Holdings Channel reports. The fund owned 35,709 shares of the electric vehicle producer’s stock after acquiring an additional 9,342 shares during …',
     'url': 'https://www.etfdailynews.com/2025/01/03/tesla-inc-nasdaqtsla-shares-bought-by-gamma-investing-llc/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-03T11:26:57Z',
     'content': 'GAMMA Investing LLC raised its stake in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 35.4% during the 4th quarter, Holdings Channel reports. The fund owned 35,709 shares of the electric vehicle produce… [+6447 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Czech National Bank Boosts Stock Holdings in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Czech National Bank grew its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 7.1% in the 4th quarter, according to the company in its most recent filing with the SEC. The firm owned 605,404 shares of the electric vehicle producer’s stock after buying a…',
     'url': 'https://www.etfdailynews.com/2025/01/13/czech-national-bank-boosts-stock-holdings-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-13T13:08:48Z',
     'content': 'Czech National Bank grew its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 7.1% in the 4th quarter, according to the company in its most recent filing with the SEC. The firm owned 605,404 sh… [+6034 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Clarius Group LLC Sells 2,737 Shares of Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Clarius Group LLC decreased its stake in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 8.6% during the fourth quarter, Holdings Channel reports. The firm owned 28,983 shares of the electric vehicle producer’s stock after selling 2,737 shares during the…',
     'url': 'https://www.etfdailynews.com/2025/01/21/clarius-group-llc-sells-2737-shares-of-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-21T11:16:50Z',
     'content': 'Clarius Group LLC decreased its stake in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 8.6% during the fourth quarter, Holdings Channel reports. The firm owned 28,983 shares of the electric ve… [+6151 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Joule Financial LLC Reduces Stock Position in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Joule Financial LLC cut its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 1.0% during the fourth quarter, according to its most recent Form 13F filing with the SEC. The firm owned 7,649 shares of the electric vehicle producer’s stock after selling 78…',
     'url': 'https://www.etfdailynews.com/2025/01/21/joule-financial-llc-reduces-stock-position-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-21T11:16:49Z',
     'content': 'Joule Financial LLC cut its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 1.0% during the fourth quarter, according to its most recent Form 13F filing with the SEC. The firm owned 7,649 shar… [+6189 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Shares Purchased by BNC Wealth Management LLC',
     'description': 'BNC Wealth Management LLC boosted its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 2.1% in the 4th quarter, Holdings Channel.com reports. The institutional investor owned 40,946 shares of the electric vehicle producer’s stock after buying …',
     'url': 'https://www.etfdailynews.com/2025/01/21/tesla-inc-nasdaqtsla-shares-purchased-by-bnc-wealth-management-llc/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-21T10:44:46Z',
     'content': 'BNC Wealth Management LLC boosted its position in shares of Tesla, Inc. (NASDAQ:TSLA – Free Report) by 2.1% in the 4th quarter, Holdings Channel.com reports. The institutional investor owned 40,946 s… [+6323 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Franchise Capital Ltd Cuts Stock Position in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Franchise Capital Ltd lowered its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 63.2% in the 4th quarter, according to the company in its most recent disclosure with the Securities and Exchange Commission (SEC). The fund owned 10,680 shares of the el…',
     'url': 'https://www.etfdailynews.com/2025/01/03/franchise-capital-ltd-cuts-stock-position-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-03T12:01:19Z',
     'content': 'Franchise Capital Ltd lowered its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 63.2% in the 4th quarter, according to the company in its most recent disclosure with the Securities and Excha… [+5890 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Vaibhav Taneja Sells 7,000 Shares of Tesla, Inc. (NASDAQ:TSLA) Stock',
     'description': 'Tesla, Inc. (NASDAQ:TSLA – Get Free Report) CFO Vaibhav Taneja sold 7,000 shares of Tesla stock in a transaction that occurred on Monday, January 6th. The shares were sold at an average price of $413.56, for a total transaction of $2,894,920.00. Following the…',
     'url': 'https://www.etfdailynews.com/2025/01/10/vaibhav-taneja-sells-7000-shares-of-tesla-inc-nasdaqtsla-stock/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-10T09:46:44Z',
     'content': 'Tesla, Inc. (NASDAQ:TSLA – Get Free Report) CFO Vaibhav Taneja sold 7,000 shares of Tesla stock in a transaction that occurred on Monday, January 6th. The shares were sold at an average price of $413… [+6181 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Shares Bought by Empirical Asset Management LLC',
     'description': 'Empirical Asset Management LLC raised its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 1,739.1% in the 4th quarter, Holdings Channel reports. The fund owned 58,282 shares of the electric vehicle producer’s stock after acquiring an additional 55,113 …',
     'url': 'https://www.etfdailynews.com/2025/01/19/tesla-inc-nasdaqtsla-shares-bought-by-empirical-asset-management-llc/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-19T09:01:08Z',
     'content': 'Empirical Asset Management LLC raised its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 1,739.1% in the 4th quarter, Holdings Channel reports. The fund owned 58,282 shares of the electric ve… [+6275 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Shares Purchased by Aaron Wealth Advisors LLC',
     'description': 'Aaron Wealth Advisors LLC increased its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 25.0% in the fourth quarter, HoldingsChannel.com reports. The firm owned 13,410 shares of the electric vehicle producer’s stock after buying an additional 2,680 sha…',
     'url': 'https://www.etfdailynews.com/2025/01/21/tesla-inc-nasdaqtsla-shares-purchased-by-aaron-wealth-advisors-llc/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-21T09:35:18Z',
     'content': 'Aaron Wealth Advisors LLC increased its holdings in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 25.0% in the fourth quarter, HoldingsChannel.com reports. The firm owned 13,410 shares of the electric v… [+6603 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Sandbox Financial Partners LLC Lowers Stake in Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Sandbox Financial Partners LLC trimmed its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 23.9% during the fourth quarter, HoldingsChannel.com reports. The firm owned 739 shares of the electric vehicle producer’s stock after selling 232 shares during …',
     'url': 'https://www.etfdailynews.com/2025/01/21/sandbox-financial-partners-llc-lowers-stake-in-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-21T09:01:09Z',
     'content': 'Sandbox Financial Partners LLC trimmed its position in Tesla, Inc. (NASDAQ:TSLA – Free Report) by 23.9% during the fourth quarter, HoldingsChannel.com reports. The firm owned 739 shares of the electr… [+6435 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Rep. Michael Guest Purchases Shares of Tesla, Inc. (NASDAQ:TSLA)',
     'description': 'Representative Michael Guest (R-Mississippi) recently bought shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on December 20th, the Representative disclosed that they had bought between $1,001 and $15,000 in Tesla stock on November 8th. The trade oc…',
     'url': 'https://www.etfdailynews.com/2024/12/24/rep-michael-guest-purchases-shares-of-tesla-inc-nasdaqtsla/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2024-12-24T08:34:53Z',
     'content': 'Representative Michael Guest (R-Mississippi) recently bought shares of Tesla, Inc. (NASDAQ:TSLA). In a filing disclosed on December 20th, the Representative disclosed that they had bought between $1,… [+7233 chars]'},
    {'source': {'id': None, 'name': 'ETF Daily News'}, 'author': 'MarketBeat News',
     'title': 'Tesla, Inc. (NASDAQ:TSLA) Given Average Recommendation of “Hold” by Analysts',
     'description': 'Shares of Tesla, Inc. (NASDAQ:TSLA – Get Free Report) have been given a consensus rating of “Hold” by the forty ratings firms that are covering the company, Marketbeat Ratings reports. Nine analysts have rated the stock with a sell rating, fourteen have issue…',
     'url': 'https://www.etfdailynews.com/2025/01/13/tesla-inc-nasdaqtsla-given-average-recommendation-of-hold-by-analysts/',
     'urlToImage': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/tesla-inc-logo-1200x675.png?v=20221020135629&w=240&h=240&zc=2',
     'publishedAt': '2025-01-13T09:42:43Z',
     'content': 'Shares of Tesla, Inc. (NASDAQ:TSLA – Get Free Report) have been given a consensus rating of “Hold” by the forty ratings firms that are covering the company, Marketbeat Ratings reports. Nine analysts … [+5568 chars]'}
  ],
}